### PR TITLE
Ctx loader

### PR DESCRIPTION
**Pull request by aeneasr**

### CODE REVIEW

**Comment by per1234** [comment]
Should this be considered a major breaking change to the public API @aeneasr?

**Comment by aeneasr** [comment]
Yes, we only use this fork internally though. I'd recommend using the upstream for anyone else

**Comment by per1234** [comment]
That is very unfortunate. I have a requirement for https://github.com/santhosh-tekuri/jsonschema/issues/33 and so am not able to use the upstream.

I suggest that you add a note to the readme so that the maintenance status is clear and others are not led into the expectation of a reliable API.

Anyway, thank you for sharing your code.

**Comment by aeneasr** [comment]
Sorry about that! If you use the lib, just add `context.Background()` to the calls, then it should work :) Will add a note!

**Pull request merged**
